// <auto-generated />
namespace MatRoleClaim.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_tbl_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_tbl_User));
        
        string IMigrationMetadata.Id
        {
            get { return "202109061316379_update_tbl_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
